# Generated by Django 4.1.5 on 2023-01-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='img',
            field=models.FileField(upload_to='pics'),
        ),
    ]
